version: "3"

services:
  db:
    container_name: go-blog_db
    image: "postgres:latest"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:
