version: "3"

services:
  db:
    container_name: go-blog_db
    image: "postgres:latest"
    env_file:
      - .env
    restart: always
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:
